/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import com.auth0.jwt.JWT
import com.auth0.jwt.algorithms.Algorithm
import io.ktor.serialization.jackson.*
import io.ktor.server.application.*
import io.ktor.http.*
import io.ktor.server.engine.*
import io.ktor.server.http.content.resource
import io.ktor.server.http.content.staticResources
import io.ktor.server.netty.*
import io.ktor.server.plugins.contentnegotiation.*
import io.ktor.server.plugins.cors.routing.CORS
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import java.time.Instant
import java.util.concurrent.ConcurrentHashMap

data class StartReq(val username: String?)
data class FinishReq(val username: String?, val txId: String?, val ownIdToken: String?)
data class User(val id: String, val username: String, val createdAt: String)
data class OwnIDData(val loginId: String?, val data: Map<String, Any?>?)
data class OwnIDSearchRequest(val loginId: String?)
data class OwnIdErrorResponse(val status: Int, val message: String)
data class OwnIDDataResponse(val data: Map<String, Any?>?)
data class OwnIDSessionResponse(val token: String)

fun main() {
    embeddedServer(Netty, port = System.getenv("PORT")?.toIntOrNull() ?: 80) { module() }.start(wait = true)
}

fun Application.module() {
    install(ContentNegotiation) { jackson() }
    install(CORS) {
        anyHost()
        allowHeader(HttpHeaders.Authorization)
        allowHeader(HttpHeaders.ContentType)
    }

    val ownIdAppId = System.getenv("OWNID_APP_ID") ?: "dev-app-id"
    val jwtSecret = System.getenv("JWT_SECRET") ?: "dev"
    val algo = Algorithm.HMAC256(jwtSecret)

    val users = ConcurrentHashMap<String, User>()
    val ownIdDataByLoginId = ConcurrentHashMap<String, Map<String, Any?>>()

    routing {
        staticResources("/static", "web", index = "sample.html")

        resource(remotePath = "/sample", resource = "web/sample.html")

        resource(remotePath = "/.well-known/assetlinks.json", resource = "web/assetlinks.json")

        get("/health") { call.respond(mapOf("ok" to true)) }

        post("/ownid/register/start") {
            val body = call.receive<StartReq>()
            val username = body.username ?: return@post call.respond(HttpStatusCode.BadRequest, mapOf("error" to "username required"))
            val txId = "reg_${System.currentTimeMillis()}_${(1..1_000_000).random()}"
            call.respond(mapOf("txId" to txId, "appId" to ownIdAppId))
        }

        post("/ownid/register/finish") {
            val body = call.receive<FinishReq>()
            val (username, txId, ownIdToken) = listOf(body.username, body.txId, body.ownIdToken)
            if (username == null || txId == null || ownIdToken == null) {
                return@post call.respond(HttpStatusCode.BadRequest, mapOf("error" to "username, txId, ownIdToken required"))
            }
            // TODO: verify ownIdToken with OwnID service
            val user = users.computeIfAbsent(username) {
                User("u_${System.currentTimeMillis()}", username, Instant.now().toString())
            }
            val appToken = JWT.create()
                .withSubject(user.id)
                .withClaim("username", user.username)
                .withExpiresAt(java.util.Date.from(Instant.now().plusSeconds(3600)))
                .sign(algo)
            call.respond(mapOf("ok" to true, "txId" to txId, "user" to user, "appToken" to appToken))
        }

        post("/ownid/login/start") {
            val body = call.receive<StartReq>()
            val username = body.username ?: return@post call.respond(HttpStatusCode.BadRequest, mapOf("error" to "username required"))
            val txId = "login_${System.currentTimeMillis()}_${(1..1_000_000).random()}"
            call.respond(mapOf("txId" to txId, "appId" to ownIdAppId, "knownUser" to users.containsKey(username)))
        }

        post("/ownid/login/finish") {
            val body = call.receive<FinishReq>()
            val (username, txId, ownIdToken) = listOf(body.username, body.txId, body.ownIdToken)
            if (username == null || txId == null || ownIdToken == null) {
                return@post call.respond(HttpStatusCode.BadRequest, mapOf("error" to "username, txId, ownIdToken required"))
            }
            val user = users[username] ?: return@post call.respond(HttpStatusCode.NotFound, mapOf("error" to "user not found"))
            // TODO: verify ownIdToken with OwnID service
            val appToken = JWT.create()
                .withSubject(user.id)
                .withClaim("username", user.username)
                .withExpiresAt(java.util.Date.from(Instant.now().plusSeconds(3600)))
                .sign(algo)
            call.respond(mapOf("ok" to true, "txId" to txId, "user" to user, "appToken" to appToken))
        }


        // OwnID integration endpoints
        post("/setOwnIDDataByLoginId") {
            val req = call.receive<OwnIDData>()
            val loginId = req.loginId
            if (loginId.isNullOrBlank()) {
                return@post call.respond(HttpStatusCode.BadRequest, mapOf("error" to "loginId required"))
            }
            val data = req.data ?: emptyMap()
            ownIdDataByLoginId[loginId] = data
            call.respond(HttpStatusCode.NoContent)
        }

        post("/getOwnIDDataByLoginId") {
            val req = call.receive<OwnIDSearchRequest>()
            val loginId = req.loginId
            if (loginId.isNullOrBlank()) {
                return@post call.respond(HttpStatusCode.OK, OwnIdErrorResponse(HttpStatusCode.BadRequest.value, "loginId required"))
            }
            val data = ownIdDataByLoginId[loginId]
            if (data == null) {
                return@post call.respond(HttpStatusCode.OK, OwnIdErrorResponse(HttpStatusCode.NotFound.value, "User not found"))
            }
            call.respond(HttpStatusCode.OK, OwnIDDataResponse(data))
        }

        post("/getSessionByLoginId") {
            val req = call.receive<OwnIDSearchRequest>()
            val loginId = req.loginId
            if (loginId.isNullOrBlank()) {
                return@post call.respond(HttpStatusCode.BadRequest, mapOf("error" to "loginId required"))
            }
            val alg = Algorithm.HMAC256(System.getenv("JWT_SECRET") ?: "dev")
            val token = JWT.create().withClaim("loginId", loginId).sign(alg)
            call.respond(HttpStatusCode.OK, OwnIDSessionResponse(token))
        }
    }
}